/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type NotificationType = "comment" | "follow" | "like" | "mention" | "message" | "share" | "system";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Ads {
  content: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  image_url: string | null;
  is_active: Generated<boolean>;
  link_url: string | null;
  script_code: string | null;
  title: string;
  type: string;
}

export interface Comments {
  content: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  post_id: number | null;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface Follows {
  created_at: Generated<Timestamp | null>;
  follower_id: number | null;
  following_id: number | null;
  id: Generated<number>;
}

export interface Likes {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  post_id: number | null;
  user_id: number | null;
}

export interface Notifications {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  is_read: Generated<boolean | null>;
  message: string;
  related_post_id: number | null;
  trigger_user_id: number | null;
  type: NotificationType;
  user_id: number | null;
}

export interface Posts {
  comments_count: Generated<number | null>;
  content: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  image_url: string | null;
  likes_count: Generated<number | null>;
  shares_count: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface Sessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: string;
  last_accessed: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface Shares {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  post_id: number | null;
  user_id: number | null;
}

export interface UserPasswords {
  created_at: Generated<Timestamp | null>;
  password_hash: string;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface Users {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp | null>;
  display_name: string;
  email: string;
  followers_count: Generated<number | null>;
  following_count: Generated<number | null>;
  id: Generated<number>;
  is_verified: Generated<boolean | null>;
  posts_count: Generated<number | null>;
  role: Generated<UserRole | null>;
  updated_at: Generated<Timestamp | null>;
  username: string | null;
}

export interface DB {
  ads: Ads;
  comments: Comments;
  follows: Follows;
  likes: Likes;
  notifications: Notifications;
  posts: Posts;
  sessions: Sessions;
  shares: Shares;
  user_passwords: UserPasswords;
  users: Users;
}
